language: csharp
solution: ./swt2/ccd/SIMS.sln
install:
  - nuget restore ./swt2/ccd/SIMS.sln
  - nuget install NUnit.Runners -Version 3.9.0 -OutputDirectory testing
  - sudo apt-get install zip
script:
  - msbuild /p:Configuration=Release ./swt2/ccd/SIMS.sln
# debug environment/build result
#  - ls -laR
# run test
  - mono  ./testing/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./swt2/ccd/SIMS/bin/Release/SIMS.exe
deploy:
  - provider: script
    script: zip -j "./swt2/ccd/SIMS/bin/$TRAVIS_TAG.zip" "./swt2/ccd/SIMS/bin/Release/SIMS.exe" "./swt2/ccd/SIMS/bin/Release/SIMS.exe.config"
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $github_releases_token
#   file_glob: true
#   file: ./swt2/ccd/SIMS/bin/Release/*
    file:
      - "./swt2/ccd/SIMS/bin/$TRAVIS_TAG.zip"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true