language: csharp
solution: ./swt2/ccd/SIMS.sln
install:
  - nuget restore ./swt2/ccd/SIMS.sln
  - nuget install NUnit.Runners -Version 3.9.0 -OutputDirectory testing
script:
  - msbuild /p:Configuration=Release ./swt2/ccd/SIMS.sln
# debug environment/build result
#  - ls -laR
# run test
  - mono  ./testing/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./swt2/ccd/SIMS/bin/Release/SIMS.exe